name: Publish MkSlides

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install mkslides

            - name: Build slides for each module
              run: |
                  for module in Module*/; do
                      if [ -d "${module}slides" ]; then
                          echo "Building slides for ${module}slides/"
                          cd $module
                          mkdir -p site
                          mkslides build -f ../mkslides.yml -d ./site slides
                          cd ..
                      else
                          echo "Skipping $module - no slides directory found"
                      fi
                  done

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: site # Deploy the generated site folder
                  branch: gh-pages # Deploy to the gh-pages branch
                  clean: true # Automatically remove existing files in the branch
