name: Publish MkSlides

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install mkslides

            - name: Build slides for each module
              run: |
                  # Create a common temporary folder for all slides
                  mkdir -p temp_slides
                  mkdir -p temp_slides/assets

                  # Copy slides from each module to the common folder
                  for module in Module*/; do
                      # Extract module number (e.g., '5' from 'Module5/')
                      module_id=$(echo $module | sed -n 's/Module\([0-9]*\)\//\1/p')
                      
                      if [ -d "${module}slides" ]; then
                          echo "Processing slides from ${module} (ID: $module_id)"
                          # Copy and prefix markdown files
                          for file in ${module}slides/*.md; do
                              if [ -f "$file" ]; then
                                  # Get just the filename without path
                                  filename=$(basename "$file")
                                  # Copy with module_id prefix
                                  cp "$file" "temp_slides/${module_id}-${filename}"
                                  echo "  Copied $filename to ${module_id}-${filename}"
                      fi
                  done

                          # Handle assets directory - merge contents
                          if [ -d "${module}slides/assets" ]; then
                              echo "  Merging assets from ${module}slides/assets"
                              cp -r "${module}slides/assets/"* temp_slides/assets/
                          fi
                      else
                          echo "Skipping $module - no slides directory found"
                      fi
                  done

                  # Run mkslides once on the combined folder
                  echo "Building slides from combined slides directory"
                  mkslides build -f mkslides.yml -d ./site temp_slides

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: site # Deploy the generated site folder
                  branch: gh-pages # Deploy to the gh-pages branch
                  clean: true # Automatically remove existing files in the branch
